name: image
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1
  - cloudpickle=1.0.0=py_0
  - colorama=0.4.1=py37_0
  - cryptography=2.6.1=py37h7a1dbc1_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.9.0.1=py37hfa6e2cd_1
  - dask-core=1.2.2=py_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - ffmpeg=4.1.3=h6538335_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - imageio=2.4.1=py37_0
  - intel-openmp=2019.3=203
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.4.0=py37_0
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.4=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - kiwisolver=1.1.0=py37ha925a31_0
  - libiconv=1.15=h1df5818_7
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.0.10=hb898794_2
  - libxml2=2.9.9=h464c3ec_0
  - libxslt=1.1.33=h579f668_0
  - lxml=4.3.3=py37h1350720_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.0.3=py37hc8f65d3_0
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.3=203
  - mkl_fft=1.0.12=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - moviepy=0.2.3.5=py_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - networkx=2.3=py_0
  - notebook=5.7.8=py37_0
  - numpy=1.16.3=py37h19fb1c0_0
  - numpy-base=1.16.3=py37hc3f5095_0
  - olefile=0.46=py37_0
  - openssl=1.1.1=he774522_0
  - palettable=3.1.1=py_0
  - pandas=0.24.2=py37ha925a31_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.0.0=py37hdc69c19_0
  - pip=19.1.1=py37_0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.4.0=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.14.11=py37he774522_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h8c8aaf0_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py37h8c2d366_1
  - pywinpty=0.5.5=py37_1000
  - pyyaml=5.1=py37he774522_0
  - pyzmq=18.0.0=py37ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.4.4=py_0
  - requests=2.21.0=py37_0
  - scikit-image=0.15.0=py37ha925a31_0
  - scipy=1.2.1=py37h29ff71c_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=he774522_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.9.0=py37_0
  - tornado=6.0.2=py37he774522_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.2=py37_0
  - vc=14.1=h21ff451_3
  - vs2015_runtime=15.5.2=3
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
prefix: C:\Users\JSB\Miniconda3\envs\image

